---
driver_plugin: xenserver

driver_config:
  xenserver_name:     'elasticsearch-kitchen'
  xenserver_password: 'steady road takes toll'
  xenserver_template: 'CentOS 6.5 (x86_64) - Wildbit'
  xenserver_url:      '10.10.1.35'
  xenserver_username: 'root'

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[wb-java::default]
    attributes:
